let shopItemsData = [
  {
    id: "q",
    name: "Men's Jacket",
    price: 15,
    img: "images/jacket-1.jpg",
    category: "Jacket",
  },
  {
    id: 'w',
    name: "Wall Clock",
    price: 30,
    img: "images/watch-3.jpg",
    category: "Watches",
  },
  {
    id: 'e',
    name: "Boot shoe",
    price: 60,
    img: "images/shoe-5.jpg",
    category: "Shoes",
  },{
    id: 'r',
    name: "series 7 ",
    price: 30,
    img: "images/watch-1.jpg",
    category: "Watches",
  },
  {
    id: 't',
    name: "Summer Short",
    price: 18,
    img: "images/shorts-1.jpg",
    category: "Clothes",
  },
  {
    id: 'y',
    name: "Sports Shoe",
    price: 120,
    img: "images/sports-6.jpg",
    category: "Shoes",
  },
  {
    id: 'u',
    name: "Winter Jacket",
    price: 80,
    img: "images/jacket-6.jpg",
    category: "Jacket",
  },
    {
    id: 'i',
    name: "Apple Watch",
    price: 250,
    img: "images/watch-2.jpg",
    category: "Watches",
  },
  {
    id: 'o',
    name: "Perfume Women",
    price: 26,
    img: "images/perfume.jpg",
    category: "Accessories",
  },
  {
    id: 'p',
    name: "Bkue Shirt",
    price: 45,
    img: "images/shirt-1.jpg",
    category: "Clothes",
  },

  {
    id: 'a',
    name: "Apple Watch",
    price: 12.99,
    img: "images/watch-4.jpg",
    category: "Watches",
  },
    {
    id: "s",
    name: "Men's Jacket",
    price: 15,
    img: "images/jacket-2.jpg",
    category: "Jacket",
  },
    {
    id: 'd',
    name: "Sports Shoe",
    price: 120,
    img: "images/sports-2.jpg",
    category: "Shoes",
  },
    {
    id: 'f',
    name: "Bkue Shirt",
    price: 45,
    img: "images/shirt-2.jpg",
    category: "Clothes",
  },
    {
    id: 'g',
    name: "Perfume Women",
    price: 26,
    img: "images/jewellery-1.jpg",
    category: "Accessories",
  },
        {
    id: 'h',
    name: "Perfume Women",
    price: 26,
    img: "images/jewellery-2.jpg",
    category: "Accessories",
  },
];
